name: Build and run tests for progit2-gr book

on:
  push


jobs:
  checkout-progit2-english-version:
    runs-on: ubuntu-latest

    name: Download progit2

    steps:
      - name: Checkout progit2-en
        uses: actions/checkout@v5
        with:
          repository: progit/progit2
          path: progit2-en
        
      - name: Checkout progit2-gr
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}  #this is the current repository
          path: progit2-gr
    
      # - name: Print the content of the current workspace
      #   run: |
      #     ls -la $GITHUB_WORKSPACE
      #     echo "This content is from the progit2-en"
      #     ls -la $GITHUB_WORKSPACE/progit2-en

      #     echo "\nThis content is from the progit2-gr"
      #     ls -la $GITHUB_WORKSPACE/progit2-gr
      
      - name: Run the english version of findHttpsLinks
        run: |
          chmod +x $GITHUB_WORKSPACE/progit2-gr/findLinks_gr
          chmod +x $GITHUB_WORKSPACE/progit2-gr/findLinks_en
          
          $GITHUB_WORKSPACE/progit2-gr/findLinks_gr $GITHUB_WORKSPACE/progit2-gr/
          $GITHUB_WORKSPACE/progit2-gr/findLinks_en $GITHUB_WORKSPACE/progit2-en/

      - name: Check the $HOME and the $HOME/progit2Results/ after the run of the executable
        run: |
          ls -la $HOME
          ls -la $HOME/progit2Results

          echo "\n\nPrint the content of the progit2Results"
          ls -la $HOME/progit2Results/allFilesFromTheRoot_en
          ls -la $HOME/progit2Results/allFilesFromTheRoot_gr
      
      - name: Diff the directories to check if there are any diffs between the files that contains https findLinks_en
        run: |
          cd $HOME
          if diff -r progit2Results/allFilesFromTheRoot_en/ progit2Results/allFilesFromTheRoot_gr/ > /dev/null; then 
          diffExitCode=$?
          echo "The exit status code is: $diffExitCode"
          if [ $diffExitCode -ne 0 ]; then
            echo "There were difference between files"
            cat diffFiles.txt
          else
            echo "All files are the same"
          fi

        
  # unfortunately, the call-workflow introduce new working directory
  # That means, I have to copy the cloned directories to the other workflow
  # which is not the best solution

  # call-workflow:
  #   if: ${{ always() }}
  #   needs: checkout-progit2-english-version
  #   name: Call the other reusable workflow
  #   uses: marrinosnis/progit2/.github/workflows/run-english-checks.yml@add-github-actions


# ${GITHUB_WORKSPACE}/progit2-gr
# ${GITHUB_WORKSPACE}/progit2-en