name: Build and run tests for progit2-gr book

on:
  push


jobs:
  checkout-progit2-english-version:
    runs-on: ubuntu-latest

    name: Download progit2

    steps:
      - name: Checkout progit2-en
        uses: actions/checkout@v5
        with:
          repository: progit/progit2
          path: progit2-en
        
      - name: Checkout progit2-gr
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}  #this is the current repository
          path: progit2-gr
    
      - name: Print the content of the current workspace
        run: |
          ls -la $GITHUB_WORKSPACE
          echo "This content is from the progit2-en"
          ls -la $GITHUB_WORKSPACE/progit2-en

          echo "\nThis content is from the progit2-gr"
          ls -la $GITHUB_WORKSPACE/progit2-gr
      
      - name: Print values
        run: |
          echo "The value of the GITHUB_REPOSITORY is"
          echo ${{ github.repository }}
      
      - name: Run the english version of findHttpsLinks
        run: |
          chmod +x $GITHUB_WORKSPACE/progit2-gr/findLinks_gr 
          $GITHUB_WORKSPACE/progit2-gr/findLinks_gr $GITHUB_WORKSPACE/progit2-gr/book/02-git-basics/sections

      - name: Check the $HOME after the run of the executable
        run: |
          ls -la ${{ github.repository }}
          ls -la ${{ github.repository }}/results
          ls -la ${{ github.repository }}/results/allFilesFromTheRoot_gr
          ls -la ${{ github.repository }}/results/check_gr

          echo "The value of GITHUB_REPOSITORY is:\n"
          echo $GITHUB_REPOSITORY

      # - name: The home directory in the github runner
      #   run: |
      #     echo "The tilda has the value of:"
      #     pwd
      #     echo ~
      #     echo $HOME

        

  # call-workflow:
  #   if: ${{ always() }}
  #   needs: checkout-progit2-english-version
  #   name: Call the other reusable workflow
  #   uses: marrinosnis/progit2/.github/workflows/run-english-checks.yml@add-github-actions

